llm:
  provider: openai
  config:
    model: 'google/gemini-2.0-flash-001'
    api_key: '${OPENROUTER_API_KEY}'
    base_url: 'https://openrouter.ai/api/v1'
    extra_headers:
      'HTTP-Referer': 'https://dk-copywriter.com'

embedder:
  provider: openai
  config:
    model: 'text-embedding-3-small'
    api_key: '${OPENAI_API_KEY}'
    base_url: 'https://api.openai.com/v1'

rag:
  chunk_size: 1000
  chunk_overlap: 200
  max_context_length: 8000
  similarity_threshold: 0.1
  max_results: 5