llm:
  provider: litellm
  config:
    model: 'openrouter/openai/gpt-5'
    api_key: '${OPENROUTER_API_KEY}'
    site_url: 'https://dk-copywriter.com'
    app_name: 'DK AI Copywriting Assistant'
    num_retries: 2
    timeout: 30
    fallback_models:
      - 'openrouter/anthropic/claude-3-5-sonnet-20241022'
      - 'openrouter/google/gemini-2.0-flash-001'

embedder:
  provider: openai
  config:
    model: 'text-embedding-3-small'
    api_key: '${OPENAI_API_KEY}'
    base_url: 'https://api.openai.com/v1'

rag:
  chunk_size: 1000
  chunk_overlap: 200
  max_context_length: 8000
  similarity_threshold: 0.1
  max_results: 5